export const SET_CURRENT_TASK = 'SET_CURRENT_TASK';
export const SET_BUSINESS_NAMES = 'SET_BUSINESS_NAMES';
export const ADD_BUSINESS_NAMES = 'ADD_BUSINESS_NAMES';
export const SET_BUSINESSES = 'SET_BUSINESSES';
export const ADD_BUSINESSES = 'ADD_BUSINESSES';
